# Generated by Django 2.0.13 on 2020-07-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_knnsuggestionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knnsuggestionmodel',
            name='distance',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='knnsuggestionmodel',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='knnsuggestionmodel',
            name='knnsuggestions',
            field=models.CharField(max_length=100),
        ),
    ]
